language: node_js
node_js:
- node
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 08094130644d
  - COMMIT_AUTHOR_EMAIL: metodiev.martin@gmail.com
branches:
  only:
  - prod
deploy:
  provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    #Alfred's key
    secure: D+wkZeQwatHmoq1nkFBlpH0+Kyt22ETcOvrxVnDVKtBkfTfjwPPf60v6FH99cHxOgPBF1N8OrSMA7VOuPWsyMmzBD4E/fq+uarxX7YV4DINXnM6+7Q0xJnK+48yHljCc0wSSmr7EyEQnC/IfVtWQFFTB68+hWObcOvrGgDJRzDTgRlXXe8yWDEoCx6dp0+TUZYsER/M0uf4WTIeVpvTKXgNTZrdRbYqPn8L6bhb35d2EYT2Q7rnWSf6C/z5f6cgZPzkwifV2f1Mwi6pm76mm3G/LyyTFfYFtdbVL2FIPvrzQLs1dM79WIkqZHhnWEbSOAEpXbQD2UFg+lIkY0LdU7O9tSKBuAierBkOnuM6XbIoxEfYx5sFosmyP/UC49VPSlSC7slJCoWjPzTrs+EU66ZpcEN3ZtSa282x7D7sW6CE6kRgGlqrnm+pKa4ib4HUHFoGexkUjo4bptXzWwzKReztAhbmmGetpN7/83JQxk8xWBtNi+pwuZn2UAdzzOAtefRqe67/wUbWIp/8vzKu01nF3B8X2FbCb+xRVb0/33eeJA5LUKAQl42DwLK8iW4jLu3rvdhSv09xeG66uTV1TMztPBYqIbukEJCD3pZJ0RAtvWRMhdnRdPb6h5rlrFwFtnF2TN0WBjetwAGV5IQB/vnGAvwyO8VX0rF9dvT7WdJs=
  on:
    tags: true