language: node_js
node_js:
- 7.8
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'memoryroll.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: y6iyb74YMiRgvQDSUG363TcRgeTmFkYld8MdPiZxQxCC/aC8QY9ni4/mnCgZfyWkOzzUi9MnvEDD9x6L28C0p0QGguHHEMn3t6e3GGmhLLSezoTNBJELTDBmtLXsKDGfqGHQK4I1zH5VQkmSMZyBdHcinNkhS4nCkwqLSASohKhn5JIXiErC0SXw9D6TH8+dm5WhRpU/2OgiJGuOhaleoL4GotpowbknYi4A5JlZYajqIUPLgRnKrpPgk5c7BuVzbkVZKDC5jd6M23dHMSQ3blNINgKgvNpVbrmMM5uukpYfXo8EPJWBmz0RXWI7eDL+ijIn1aPuI71xfJyYRQbeW0R3gZL3lYvZTAgmOLoPq13inLDrPAui+kc+PfCStFfpJ1aTAmHNh9rrOT33ZYJVoUrxQkevtRK9eKF1F+JEvlpQ8FwBflg0CYcByvycDgrc3lnIWi1R3lc/C9EoH9q8+IkDu2+/YWruGMIa5K5MPjPdA1gGc4YJmtU5NMntyZJwPVjlTSFYrTVB1iS17VoD80xTScIgjSbH5r5BMwHXmJ6vTr8S8BOkrVOdeBpexSJR1zPLrBExBIgvnEn90JzXTcLj6kn0X9muXCRM+NOPfbipCK+THI0k+T71l3+iXmhx30uZUc2cC68hcesCaZJOBQIweF6q0hP5tTS2ko/v2Zo=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: NI2ntrcSt5ZRhv0bHvemM7ZU8wm4sU3K4XiO7k1O3pcexbPDMaPorwwkYfD227I55msmLw1bpyGhCgaO2Qku9yo1sYWPshQuoxsrD71665B0x4Zwc37dOwTCgzxOpEhLl/OSQiTrLDDbIrza4HnubQWTyr9eDLuQ8+RStWQnxIcVnIwOQNqeJf68rZYfgz5wX7pCyBLWPVek2AkR0Q5gsRq+3tJPD4rWhNbuFlnn5B82A9nUzdtFj41bc7ELz6qClAGUvbLUV0POfL9OEiUNPvIhI1hWk2qt4Qy9eEyFyEbe65eyRrxEfg6zaOqrOnsH3Y+fcWXzPsekVrphyPStR7ENYpnb/hOKjCbh0DKwwgLWkpAvb6hQsAvZo9FbfNgalUxz2/BX8RoNGgE6JaXX7VoKRf59zbCTiUp70ycvhSZMySyDnymc4FBwh+k/PFcuKtg9KWi/diFa3SsDgVLXeFrJXsfhRLvlqHzfVCzu0mm9IWZA01kbBDWJzO5yWJ85CVSMMdhcZpC65dllZh3EBysABdjo/7LMDpMTxtz5Fzq+leokGhhdvqN0q+IQVjOCfxtzTq6gPURDE8bH0DSh3tve9dRt2kjfWyJaRDdfaPo2Ero37YVnnqkfyRrNcZNJyRPyNu+6Y5LBgCnlX33jAf2NDk9m+Y2Mff/ANZJ8sFE=
  on:
    tags: true
- provider: releases
  api_key:
    secure: NI2ntrcSt5ZRhv0bHvemM7ZU8wm4sU3K4XiO7k1O3pcexbPDMaPorwwkYfD227I55msmLw1bpyGhCgaO2Qku9yo1sYWPshQuoxsrD71665B0x4Zwc37dOwTCgzxOpEhLl/OSQiTrLDDbIrza4HnubQWTyr9eDLuQ8+RStWQnxIcVnIwOQNqeJf68rZYfgz5wX7pCyBLWPVek2AkR0Q5gsRq+3tJPD4rWhNbuFlnn5B82A9nUzdtFj41bc7ELz6qClAGUvbLUV0POfL9OEiUNPvIhI1hWk2qt4Qy9eEyFyEbe65eyRrxEfg6zaOqrOnsH3Y+fcWXzPsekVrphyPStR7ENYpnb/hOKjCbh0DKwwgLWkpAvb6hQsAvZo9FbfNgalUxz2/BX8RoNGgE6JaXX7VoKRf59zbCTiUp70ycvhSZMySyDnymc4FBwh+k/PFcuKtg9KWi/diFa3SsDgVLXeFrJXsfhRLvlqHzfVCzu0mm9IWZA01kbBDWJzO5yWJ85CVSMMdhcZpC65dllZh3EBysABdjo/7LMDpMTxtz5Fzq+leokGhhdvqN0q+IQVjOCfxtzTq6gPURDE8bH0DSh3tve9dRt2kjfWyJaRDdfaPo2Ero37YVnnqkfyRrNcZNJyRPyNu+6Y5LBgCnlX33jAf2NDk9m+Y2Mff/ANZJ8sFE=
  skip_cleanup: true
  on:
    tags: true
