language: node_js
node_js:
- node
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 08094130644d
  - COMMIT_AUTHOR_EMAIL: metodiev.martin@gmail.com
branches:
  only:
  - "/v\\d+\\.\\d+\\.\\d+/"
deploy:
  provider: npm
  email: metodiev.martin@gmail.com
  api_key: # …36bbe381
    secure: WX2xdf+JE0rPW3StXC4sRAEfGzGKwpUTP6PswaKYNOzas5l47Jp1HiPIPylkyPEbpMzSIWl5xSENh/P/c273amlLzrVukDFEG3j5HoK9anepQVFXD47yMku4VHGxHotANsIeBZSavRmqZw1UkkrUPoZXJ07t/gy9N6QNktFc3TAEcRq7Dn5UoNYf8KzqhnLrHulDSS07nftOEu6vZvV2mLMIxLSmj9uty5exhO5jTkh05L0s+bxJfR5/dquiNgnlMpQdRK2iOxU/mIAkVfG2OQqPNXNIvw+IimzGmf9uyd89dcvOIwprC6k4+eUm8NSfJFs03LOrclQf6srP0bxhbjfXpLDlqnSmeAKjcBa5FJykcfPgGZH8ETeEXTf1asCv+KkrhufDfcxrQ86ZaQb45yTUDyoBYIowXSFfOC5qsHDjJoQ+OO+NY0Osh6QgAlVoAPX7VtpVD7NlvV6UTuf2GJcEIZEwLL1fhnPRqHdA1TnsaE9MEtnOoUASAr004kWVVX8jO2M6G2LB/bDG7un7Fumq0o/CSxEc4EUkxsvz25cB0cdcnTC7lJoC/1fKuCSLk2cQGGbrj5nCB/p1weXTVg/9lVh71xhYrgL9Nk1kGlI7IRwZuWRDP+NthClMOA5n9jFnCxnB4hlFGjQroHzMNAfle7/7Szk7Vc+3bpO6TwU=
  on:
    tags: true
    all_branches: true
